# https://docs.docker.com/build/ci/github-actions/multi-platform/
name: Publish Docker image multi-arch

on:
  push:
    branches:
      - master
      - devel
  workflow_dispatch:
  schedule:
    - cron: "0 13 * * *"

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: 
          - master
          - devel
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          context: git
          images: pipeittodevnull/nginx-certbot
          flavor: latest=true
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
