# https://docs.docker.com/build/ci/github-actions/multi-platform/
name: Publish Docker image multi-arch

on:
  push:
    branches:
      - master
      - devel
  workflow_dispatch:
  schedule:
    - cron: "0 13 * * *"

env:
  REGISTRY: ghcr.io
  IMAGE: ${{ github.repository }}

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: 
          - master
          - devel
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          image: ghcr.io/pipeittodevnull/nginx-certbot:devel
          artifact-name: ${{ env.IMAGE }}-${{ matrix.branch }}.spdx
          format: spdx-json
          upload-artifact: true
          upload-artifact-retention: 7

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true